name: Terraform AWS Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create terraform.tfvars
      run: |
        echo 'vpc_id = "${{ secrets.VPC_ID }}"' > terraform.tfvars
        echo 'security_group_name = "${{ secrets.SECURITY_GROUP_NAME }}"' >> terraform.tfvars
        echo 'db_username = "${{ secrets.DB_USERNAME }}"' > terraform.tfvars
        echo 'db_password = "${{ secrets.DB_PASSWORD }}"' >> terraform.tfvars
    

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars" -out=tfplan

    - name: Terraform Apply
      run: terraform apply -input=false tfplan

    - name: Terraform Show Outputs
      run: terraform output